with-backed/backed-interface

components/LoanHeader/LoanHeader.tsx, components/RepaymentInfo/RepaymentInfo.tsx, hooks/useLoanDetails/useLoanDetails.ts
Introducing and using some longer-form formatting in various parts of the app.
=> fix: use longer-form number rendering

components/LoanHeader/LoanHeader.tsx
=> fix: accruing doesn't overflow on mobile

jest.config.js, lib/getNFTInfo.ts, lib/nftPort.ts
=> fix: avoid loading HTML nft media

components/AdvancedSearch/AdvancedSearch.tsx, components/AdvancedSearch/CollateralInput.tsx, components/AdvancedSearch/LoanNumericInput.tsx, components/AdvancedSearch/SearchTextInput.tsx
=> NFT-262: Check negative numbers on search input

components/Custom404/Custom404.tsx, components/Custom500/Custom500.tsx, lib/constants.ts
=> NFT-263 fix: use correct channel name on 404/500

lib/loans/collateralSaleInfo.ts
Special case for 0x0 payment token (eth)
=> trivial: support eth sales

components/AdvancedSearch/AdvancedSearch.tsx, components/AdvancedSearch/Header.tsx, components/AdvancedSearch/LendabilityDropdown.tsx, pages/index.tsx
https://user-images.githubusercontent.com/7279416/165809613-be209bbf-2ed4-437c-96d4-139bbdfdfa77.mov
=> NFT-256: Lendability filter

lib/chainEnv.ts, lib/coingecko.ts, lib/events/consumers/userNotifications/emails/emails.ts, lib/loans/collateralSaleInfo.ts, lib/nftCollectionStats/index.ts, lib/nftCollectionStats/mockData.ts, lib/nftCollectionStats/nftPort.ts, lib/nftCollectionStats/quixotic.ts, stories/LoanInfo.stories.tsx
Also overall making getting sales info more extensible for when we add more chains
=> NFT-313: Hook up Quixotic API for sales info on optimism

__tests__/components/Banner.test.tsx, __tests__/components/NetworkSelector.test.tsx, components/Banner/Banner.module.css, components/Banner/messages/WrongNetwork.tsx, components/NetworkSelector/NetworkSelector.module.css, components/NetworkSelector/NetworkSelector.tsx, components/NetworkSelector/index.ts, components/PawnShopHeader/PawnShopHeader.module.css, components/PawnShopHeader/PawnShopHeader.tsx, components/Select/Select.tsx
=> NFT-324 feat: introducing NetworkSelector

components/Profile/ProfileHeader.tsx
Not 100% sure why this happened or how it started, but doing this stops the modal from appearing when it's hidden. Will investigate more in the future.
=> fix: stop inadvertent notifications modal

__tests__/lib/account.test.ts, __tests__/lib/loans/loanById.test.ts, components/Button/AllowButton.tsx, components/CreatePageHeader/AuthorizeNFTButton.tsx, components/CreatePageHeader/CreatePageForm.tsx, components/CreatePageHeader/CreatePageHeader.tsx, components/LoanForm/LoanForm.tsx, components/LoanForm/LoanFormEarlyClosure/LoanFormEarlyClosure.tsx, components/LoanForm/LoanFormRepay/LoanFormRepay.tsx, components/LoanForm/LoanFormSeizeCollateral/LoanFormSeizeCollateral.tsx, components/LoanTickets/LoanTickets.tsx, components/PawnArt/PawnArt.tsx, hooks/useLoanUnderwriter/useLoanUnderwriter.tsx, lib/account.ts, lib/authorizations/authorizeCurrency.ts, lib/contracts.ts, lib/eip721Subraph.ts, lib/loans/loanById.ts, lib/loans/node/nodeLoanById.ts, lib/loans/node/nodeLoanEventsById.ts, pages/api/network/[network]/loans/history/[id].ts, pages/network/[network]/loans/[id].tsx
This is a prerequisite for launching on polygon, since our polygon deploy doesn't have identical contract addresses
=> chore: contract directory network hierarchy

components/AdvancedSearch/Header.tsx, components/ConnectWallet/ConnectWallet.tsx, lib/config.ts, pages/_document.tsx
=> NFT-343 feat: analytics events around search and wallet connection

lib/config.ts
=> :shipit: feat: polygon enabled

__tests__/components/DisplayCurrency.test.tsx, components/AdvancedSearch/LoanNumericInput.tsx, components/AdvancedSearch/SearchTextInput.tsx, components/DisplayCurrency/DisplayCurrency.tsx, components/RepaymentInfo/RepaymentInfo.tsx
A few lint violations snuck into `main`, cleaning them up.
=> fix: various lint fixes

components/OpenGraph/OpenGraph.tsx, components/OpenGraph/index.ts, pages/api/network/[network]/nftInfo/[contractAddress]/[tokenId].ts, pages/network/[network]/loans/[id].tsx
see: https://www.opengraph.xyz/url/https%3A%2F%2Finterface-git-cjn-og-backed.vercel.app%2Fnetwork%2Fethereum%2Floans%2F63%2F/
=> NFT-345 feat: opengraph on loan page

components/ApplicationProviders/ApplicationProviders.tsx, components/DisplayAddress/DisplayAddress.tsx, lib/config.ts, package.json, yarn.lock
This appears to be a straightforward upgrade, will test out on the deployed version
=> config: upgrade rainbowkit, wagmi

pages/network/[network]/loans/[id].tsx
=> fix: more rinkeby error handling

components/Profile/ProfileHeader.tsx, components/Profile/ProfileLoans.tsx
| profile with closed loan | profile with active loan |
| -------- | -------- |
| ![image](https://user-images.githubusercontent.com/9300702/171255903-647ba282-0230-4aca-8757-bb2eca9a739c.png) | ![image](https://user-images.githubusercontent.com/9300702/171255952-17749cd3-566d-4165-82ae-f76f903186d7.png) |
=> NFT-369 fix: hide closed loans on profile page

components/ApplicationProviders/ApplicationProviders.tsx, package.json, yarn.lock
=> NFT-327 feat: add TOS to wallet connection modal

package.json, yarn.lock
Will need to test on the deploy URL
=> chore: update wagmi and rainbowkit

codegen/community.yml, graphql/community/communityAccountQuery.graphql
Small piece of scaffolding taken from #722
=> feat: codegen for community subgraph

__tests__/lib/community.test.ts, lib/community.ts
taken from #722, added a bit of testing
=> feat: more community lib helpers

components/CommunityHeader/CommunityHeader.module.css, components/CommunityHeader/CommunityHeader.tsx
| disconnected | connected |
| ------- | ------- |
| ![image](https://user-images.githubusercontent.com/9300702/178746101-0725a4af-fddc-4a98-882d-b218190f122e.png) | ![image](https://user-images.githubusercontent.com/9300702/178749105-46a140a6-94d7-4756-8134-d4bca9da9c96.png) |
=> [NFT-402] fix: indicate user should connect wallet

components/ApplicationProviders/ApplicationProviders.tsx
This should result in proper autoconnection if the user connects but their wallet is on a different network.
Supersedes #752 (thanks @nickbytes!)
=> feat: order chains with current network first

__tests__/components/CommunityActivity.test.tsx, components/CommunityActivity/CommunityActivity.module.css, components/CommunityActivity/CommunityActivity.tsx, graphql/community/communityAccountQuery.graphql, lib/community.ts
See the following for demos:
- https://interface-git-cjn-reasons-backed.vercel.app/community/0xF936A831163a5709f9680F86633A9AA9812381c5
- https://interface-git-cjn-reasons-backed.vercel.app/community/0xbc3ed6B537f2980e66f396Fe14210A56ba3f72C4
=> NFT-400 feat: displaying reason for XP award

components/CommunityActivity/CommunityActivity.module.css, components/CommunityActivity/CommunityActivity.tsx
- date in community XP award links to multisig transaction to approve XP
- added more margin per design feedback
=> NFT-400 fix: link to multisig tx, more margin

__tests__/api/events/community/nominationMessage.test.ts, __tests__/lib/events/consumers/discord/formatter.test.ts, lib/events/consumers/discord/bot.ts, lib/events/consumers/discord/formatter.ts, pages/api/events/community/nominationMessage.ts
This PR adds the API that the google form will call when a nomination is submitted
=> NFT-420: Discord channel for nominations

.env.development, lib/events/timely/timely.ts, package.json
Not ideal, but this all works on rinkeby/testnet, so adding log statements to help me debug in prod. My inkling is theres something different with the production DB that I do not know about.
=> trivial: debug timely with logs

__tests__/hooks/useCommunityGradient.test.tsx, components/ApplicationProviders/ApplicationProviders.tsx, components/CommunityHeader/CommunityHeader.tsx, components/layouts/AppWrapper.module.css, components/layouts/AppWrapper.tsx, hooks/useCommunityGradient/index.ts, hooks/useCommunityGradient/useCommunityGradient.tsx
some addresses for viewing results:
- https://interface-git-cjn-gradient-backed.vercel.app/community
- https://interface-git-cjn-gradient-backed.vercel.app/community/0xbc3ed6B537f2980e66f396Fe14210A56ba3f72C4
- https://interface-git-cjn-gradient-backed.vercel.app/community/0xF936A831163a5709f9680F86633A9AA9812381c5
=> NFT-424 feat: gradient on community page matches current accessory (when selected)

components/CollateralInfo/CollateralInfo.module.css, components/CollateralInfo/CollateralInfo.tsx, components/DescriptionList/DescriptionList.module.css, components/DisplayCurrency/DisplayCurrency.tsx, components/DisplayCurrency/index.ts, components/LoanHeader/LoanHeader.module.css, components/LoanHeader/LoanHeader.tsx, hooks/useCachedRates/useCachedRates.tsx, lib/coingecko.ts, pages/network/[network]/loans/[id].tsx, stories/LoanHeader.stories.tsx
=> NFT-374 feat: Show LTV and USD conversion on loan page

components/CreatePageHeader/CreatePageHeader.tsx, components/CreatePageHeader/Explainer.tsx, components/LoanHeader/LoanHeader.tsx, hooks/useLTV/index.ts, hooks/useLTV/useLTV.ts
=> NFT-435 feat: show LTV when creating a loan
