with-backed/backed-interface

components/CreatePageHeader/Explainer.tsx
components/LoanTermsDisclosure/LoanTermsDisclosure.tsx
jest.config.js

Some calculations on loan forms react instantly, and if the user inputs something that doesn't parse as a number yet (e.g., `.` only) the BigNumber constructor throws. In each case now we defer rendering until all fields are really filled

fix: check NaN before BigNumber

---

lib/loans/node/nodeLoanById.ts

When getting the loan from the node, this caused us to load the wrong tokenURI (and sometimes an invalid tokenURI); this was reported in Discord when a user noticed briefly seeing the wrong token art on their loan.

fix: get tokenURI by collateralTokenId

---

components/CollateralInfo/CollateralInfo.tsx
lib/nftPort.ts

In prod there's a 500 error when loading `/loans/21`.
Here's the error I see locally:
Guessing NFTPort doesn't have info for this one, and we're assuming we'll always get a number back from the api. Making it more explicit that we may not get data, and handling on frontend. It'll render like this when we don't have the data:

fix: handle undefined in nftPort response

---

pages/_app.tsx

The default wallet option in the rainbowkit list is Rainbow (which is fair), though it was raised to us that Rainbow is a less common wallet than others, and users might expect to see a more familiar one at the top. In the interest of maintaining a simpler implementation (because the API for doing this is not stable) and to avoid any particular bias, this PR sorts the default list of wallets alphabetically. In the future we could weight each position by adoption percentage.

chore: default wallet list sorted alphabetically

---

lib/events/consumers/discord/attachments.ts
lib/events/consumers/twitter/attachments.ts
lib/getNFTInfo.ts
pages/api/nftInfo/[uri].ts

This clears up some CORS noise we got on the client side; also makes sure we accurately detect things because the client-side HEAD request was guaranteed to fail.
e.g., this allows `/loans/11` to load

NFT-239 feat: nftInfo api provides media mime type

---

pages/api/nftInfo/[uri].ts

The largest group of errors we've logged to Sentry are [FetchError: invalid json response body at...](https://sentry.io/organizations/non-fungible-finance/issues/3210944660/?project=6318688) 
When we try to fetch some token metadata from IPFS instead of json we get back text that says something like:
```
ipfs resolve -r /ipfs/QmXuEFJVjQrHX7GRWY2WnbUP59re3WsyDLZoKqXvRPSxBY/1083: no link named "1083" under QmXuEFJVjQrHX7GRWY2WnbUP59re3WsyDLZoKqXvRPSxBY
- The root CID exists but the child file does not. - ERR_ID:00020
```
These seem to entirely be on rinkeby, particularly for the Monarchs. For example, http://rinkeby.withbacked.xyz/loans/133 (see OpenSea link to confirm this is not on our end). This PR does not log these errors, as there isn't anything we can do about them.

fix: ignore non-resolveable cid

---

__tests__/components/LoanTickets.test.tsx
__tests__/lib/getNFTInfo.test.ts
jest.setup.js
lib/getNFTInfo.ts
pages/api/nftInfo/[uri].ts

The NFTInfo API has been a source of some problems, breaking it into pieces to make it more testable. Also fixes bug where data URIs didn't provide the expected mime types

chore: factor nftInfo methods into lib/

---

lib/events/consumers/getNftInfoForAttachment.ts

Just conforms NFTResponseInfo type similarly to other ways it is used throughout codebase. Instead of .image, we can now safely do .image.mediaUrl

trivial: use Media type in bot attachments

---

components/LoanCard/LoanCard.tsx

| before | after |
| ------ | ------ |
| ![image](https://user-images.githubusercontent.com/9300702/165546002-ec3b40e8-1568-4070-a0d2-95ebeb8062f8.png) | ![image](https://user-images.githubusercontent.com/9300702/165546078-60325bb8-f66e-4a8f-b08b-18062298fbab.png) |
When we last updated the loancard styles we forgot to treat the loading fallback the same way, this PR updates and everything feels a bit nicer, since the homepage doesn't jump around nearly as much while loading images

NFT-298 fix: fallback wrapped with media container

---

pages/network/[network]/loans/[id].tsx

We had a path that didn't get the network prefix so it would automatically try to redirect to mainnet

fix: incorrect redirect

---

lib/nftSalesSubgraph.ts

When on Rinkeby we generate mock sales data for NFTs just so we have something to render on the page. The original generation code would produce values that couldn't be parsed as BigNumbers so we'd get 500 errors on loan pages. This PR makes it return a constant amount that does not produce issues.

fix: fixed price on mock sale data

---

components/LoanCard/LoanCard.module.css
components/Media/Media.module.css

Last time we adjusted the `<Media>` component for use on `<LoanCard>` we accidentally made it so that the image would chase the form down the page. This PR updates it so that we only position the image to the bottom in the `<LoanCard>`
| before | after |
| ----- | ----- |
| ![image](https://user-images.githubusercontent.com/9300702/168335290-98931511-9728-46b0-8b61-8d1f3d11ca30.png) | ![image](https://user-images.githubusercontent.com/9300702/168335392-daee1462-f576-44c6-8055-ef13daaf2a47.png) |

fix: object-position:bottom only on LoanCard

---

lib/getNFTInfo.ts

fixes: https://sentry.io/organizations/non-fungible-finance/issues/3271283999/?project=6318688&query=is%3Aunresolved
Basically, we would just yeet all possible media url fields into fetch to try and get the mime type. This caused a lot of errors to be logged when we would try to fetch nonexistent URLs -- now we return early when we don't have a URL to look at.

fix: don't fetch undefined media URLs

---

lib/events/consumers/attachmentsHelper.ts
lib/events/consumers/discord/attachments.ts
lib/events/consumers/discord/formatter.ts
lib/events/consumers/twitter/attachments.ts
lib/events/consumers/twitter/formatter.ts

Will go along with: https://github.com/with-backed/svg-to-png-buffer/pull/2
This PR passes the NFT contract address to our PNG buffer generator API so that it knows to generate univ3 buffers in a different way

NFT-337: Pass contract address to png buffer to fix UniV3

---

__tests__/hooks/useNetworkSpecificStyles.test.ts
components/Banner/Banner.module.css
components/Banner/Banner.tsx
components/Banner/messages/WrongNetwork.tsx
components/PawnShopHeader/PawnShopHeader.tsx
hooks/useNetworkSpecificStyles/index.ts
hooks/useNetworkSpecificStyles/useNetworkSpecificStyles.ts
pages/_app.tsx
styles/global.css

Let's make these backgrounds optimism-branded to help make sure people realize the difference. 
The "switch to Optimism" banner uses new colors:
`optimistic-red-10: #FFF5F4`
`optimistic-red-100: #FE0420`
and the --background-radial-gradient updates it's second value from `#f6f2f0` to `optimistic-red-10` . We can use this background on the Profile page too, but Loan pages keep their unique background.
While we're rigging this up, we might as well add polygon-purple for later:
`polygon-purple-10: #F8F5FF`
`polygon-purple-100: #7B3FE4`

NFT-339 feat: dynamic css for optimism & polygon

---

components/Button/AllowButton.tsx
components/CreatePageHeader/AuthorizeNFTButton.tsx
components/CreatePageHeader/CreatePageForm.tsx
components/LoanForm/LoanFormEarlyClosure/LoanFormEarlyClosure.tsx
components/LoanForm/LoanFormRepay/LoanFormRepay.tsx
components/LoanForm/LoanFormSeizeCollateral/LoanFormSeizeCollateral.tsx
hooks/useLoanUnderwriter/useLoanUnderwriter.tsx

Got some reports that `signer` wasn't available when people tried to perform transactions. Haven't been able to repro yet and formulating a plan to better handle that case. In the meantime, `useSigner` accepts an `onError` param that I'm adding here to get more visibility into this issue.

NFT-349 chore: onError param for useSigner

---

components/LoanForm/LoanForm.tsx
components/LoanForm/LoanFormBetterTerms/LoanFormBetterTerms.tsx
components/LoanForm/strings.ts

This PR updates the buyout text to make it more clear what happens during a buyout. Additionally, put some repeated strings into constants for easier updating. AFAICT these are the main repeated strings, though perhaps we'd eventually put form labels, etc. in there.

NFT-323 feat: start to use string constants on LoanForm

---

components/Media/Media.tsx

This will defer loading of images that aren't near the viewport. see: https://caniuse.com/loading-lazy-attr
Could be a minor perf gain

chore: loading="lazy" on NFT media

---

pages/api/network/[network]/nftInfo/[contractAddress]/[tokenId].ts

I guess try-catch doesn't work like normal in NextJS api routes? :man_shrugging: 
The issue Wilson reported with 500s on Rinkeby should have been caught at the top level, but instead I had to handle in each function. I even wrote up a demo program to make sure I didn't forget how this is supposed to work:
```javascript
async function main() {
try {
await throwParent();
} catch (e) {
console.log(`got an error: ${e.message}`);
}
}
async function thrower() {
throw new Error('whoops!');
}
async function throwParent() {
await thrower();
}
main();
```
and the top-level catch does perform as expected. welp.

fix: try-catches in nftInfo api

---

__tests__/components/NetworkSelector.test.tsx
components/ApplicationProviders/ApplicationProviders.tsx
components/NetworkSelector/NetworkSelector.tsx
components/PawnShopHeader/PawnShopHeader.tsx

wagmi doesn't like it when the client gets recreated. This occurred when navigating between pages, and also when changing networks. The fix is to stabilize the dependencies for the client creation so it doesn't re-spin, and also to make it so that changing network forces a full page load.
This should resolve our signer issues once and for all.

fix: no signer after page navigation

---

pages/_document.tsx

The preload wouldn't work since we didn't set this attribute (didn't need it before since we were on same domain as fonts)

fix: set crossorigin on font preload

---

__tests__/components/ErrorBanners.test.tsx
components/ErrorBanners/ErrorBanners.module.css
components/ErrorBanners/ErrorBanners.tsx
components/ErrorBanners/index.ts
components/Header/Header.module.css
pages/_app.tsx

In #384 we accidentally removed the error banners, since they were part of the old header. This PR adds them back as their own separate component.

fix: add back error banners

---

components/AdvancedSearch/Header.tsx
components/ConnectWallet/ConnectWallet.tsx
components/NFTCollateralPicker/NFTCollateralPicker.tsx
lib/pirsch.ts

This happened on Firefox with an adblocker; disabling adblocker fixed it. When window.pirsch isn't present the error blocked launching the wallet modal. Now we have a wrapper function that always checks before using.

fix: pirsch sometimes not available

---

__tests__/lib/community.test.ts
graphql/community/accessoriesQuery.graphql
lib/community.ts
lib/constants.ts

pulled from #722, this is a wrapper function that gets all the accessories from the graph and creates a lookup table where you can find an accessory by any of: name, id, or contract address.

feat: get all accessories from Graph

---

components/Select/Select.tsx

taken from #722, giving its own PR since it isn't strictly related to community page. Just makes it so we have a blue chevron when we're on the blue Select variant. This was a QA request from @jringenberg

fix: matching color for clickable Select

---

components/CreatePageHeader/CreatePageForm.tsx

We received a report on discord about a user being unable to set their allowance for MATIC. It turns out that MATIC doesn't allow you to set an allowance.
This PR filters out MATIC from the list of available tokens (doing this client-side for now as a quick fix). Verified that before this filter, there were 17 available assets on Polygon; after the filter there were 16.

fix: don't allow loans denominated in MATIC

---

components/CommunityHeader/CommunityHeader.tsx
components/ErrorBanners/ErrorBanners.tsx
components/EtherscanLink/EtherscanLink.tsx
components/NFTExchangeLink/NFTExchangeLink.tsx
hooks/useConfig/useConfig.tsx

Taken from #747. We had some sprawling complexity by special-casing handling of values for the community page. This PR fixes that by ensuring `useConfig` always returns the Optimism config on community routes.

fix: simplify config handling for community page

---

lib/getNFTInfo.ts

This should drastically reduce incidence of our most common Sentry error. tl;dr you can't fire off a HEAD request on a data URI to find its mimetype. This PR allows `getMimeType` to handle data URIs properly.

NFT-407 fix: Only HTTP(S) protocols are supported

---

components/CommunityHeader/CommunityHeader.module.css
components/CommunityHeader/CommunityHeader.tsx

We didn't have a TransactionButton here, so it wasn't clear that we were still waiting on some activity. This updates it so we show the pending state. 
Also includes some CSS tweaks to make things look nicer.

NFT-404 fix: TransactionButton when updating art

---

components/Header/Header.module.css

Working with React Select is a bit tricky, hard to make it size itself to its content. This way at least it always matches the width of the connect button.

NFT-427 fix: sizing network selector in header

---

__tests__/api/events/cron/processTimelyEvents.test.ts
__tests__/lib/events/timely/timely.test.ts
lib/events/timely/timely.ts
pages/api/events/cron/processTimelyEvents.ts

We were calling `overrideLastWrittenTimestamp` for every config, meaning that we were fast forwarding our timely clock 3 hours instead of 1 (mainnet, optimism polygon). This meant that users were receiving notifications way earlier than they should have. This PR fixes this, by only calling `overrideLastWrittenTimestamp` once at the handler level

NFT-428: Fix timely notifications firing off early
